"use client";

import { useState, useRef } from "react";
import Link from "next/link";
import { Upload, ChevronLeft, Download, Trophy } from "lucide-react";

interface Team {
  seed: number;
  player1: string;
  player1Rating: number;
  player1DuprId: string;
  player2: string;
  player2Rating: number;
  player2DuprId: string;
  teamRating: number;
  contact1: string;
  contact2: string;
}

interface Group {
  name: string;
  teams: Team[];
}

interface BracketSlot {
  label: string;
  isBye: boolean;
  seed: number; // 1-indexed seed number, 0 = unknown
}

interface BracketMatch {
  id: string;
  round: number;
  matchNum: number; // 1-indexed global match number
  slot1: BracketSlot;
  slot2: BracketSlot;
}

function parseCSV(text: string): Team[] {
  const lines = text.trim().split("\n");
  const teams: Team[] = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split(",").map((c) => c.trim());
    if (cols.length < 9 || !cols[0]) continue;
    const p1Rating = parseFloat(cols[1]) || 0;
    const p2Rating = parseFloat(cols[5]) || 0;
    const teamRating = parseFloat(cols[8]) || (p1Rating + p2Rating) / 2;
    teams.push({
      seed: 0,
      player1: cols[0],
      player1Rating: p1Rating,
      player1DuprId: cols[2],
      contact1: cols[3],
      player2: cols[4],
      player2Rating: p2Rating,
      player2DuprId: cols[6],
      contact2: cols[7],
      teamRating,
    });
  }
  teams.sort((a, b) => b.teamRating - a.teamRating);
  teams.forEach((t, i) => (t.seed = i + 1));
  return teams;
}

function snakeSeed(teams: Team[], numGroups: number): Group[] {
  const groups: Group[] = Array.from({ length: numGroups }, (_, i) => ({
    name: `Group ${String.fromCharCode(65 + i)}`,
    teams: [],
  }));
  let direction = 1;
  let groupIdx = 0;
  for (const team of teams) {
    groups[groupIdx].teams.push(team);
    groupIdx += direction;
    if (groupIdx >= numGroups) { groupIdx = numGroups - 1; direction = -1; }
    else if (groupIdx < 0) { groupIdx = 0; direction = 1; }
  }
  return groups;
}

// ─────────────────────────────────────────────────────────────────────────────
// BRACKET BUILDER — works for ANY combination of groups × qualifiers
//
// SEEDING LOGIC (standard Wimbledon/ATP/FIFA):
//
// Step 1 — Rank qualifiers into seeds:
//   Seeds are assigned by finishing position first, then group order:
//   S1 = 1st Group A (best group winner)
//   S2 = 1st Group B
//   ...
//   SG = 1st Group G (last group winner)
//   SG+1 = 2nd Group A (best runner-up)
//   SG+2 = 2nd Group B
//   ...
//   S2G = 2nd Group G
//   etc.
//
// Step 2 — Place seeds into bracket positions using standard formula:
//   For a bracket of size N (power of 2), the standard seeded positions are:
//   Generated by: seedPositions(N) which gives the seed number at each slot
//   e.g. for N=16: [1,16,9,8,5,12,13,4,3,14,11,6,7,10,15,2]
//   This ensures:
//     S1 vs S(N)   in R1 → S1 faces weakest possible opponent
//     S2 vs S(N-1) in R1 → S2 faces weakest possible opponent
//     S1 and S2 in opposite halves → can only meet in FINAL
//     S1 and S3/S4 in opposite quarters → can only meet in SF
//     S1 and S5-S8 in same half but different quarters → can meet in QF
//
// Step 3 — BYEs:
//   If N > numQualifiers, top seeds get byes.
//   numByes = N - numQualifiers
//   Seeds 1..numByes get byes: their OPPONENT slot = BYE
//   This means S1 auto-advances, S2 auto-advances, etc.
//   Whoever wins the group position gets the bye (not pre-determined by DUPR).
//
// This logic works for ANY combination:
//   8 groups × 2 qualify = 16 teams → N=16, 0 byes
//   11 groups × 2 qualify = 22 teams → N=32, 10 byes (S1-S10 get byes)
//   6 groups × 3 qualify = 18 teams → N=32, 14 byes (S1-S14 get byes)
//   etc.
// ─────────────────────────────────────────────────────────────────────────────

function buildBracket(groups: Group[], qualifiersPerGroup: number): BracketMatch[] {
  const G = groups.length;

  // Step 1: Build ordered qualifier list
  // S1 = 1st Group A, S2 = 1st Group B, ..., SG = 1st Group G
  // SG+1 = 2nd Group A, SG+2 = 2nd Group B, ...
  const qualifiers: { label: string; seed: number }[] = [];
  let seedNum = 1;
  for (let rank = 0; rank < qualifiersPerGroup; rank++) {
    const rankLabel = rank === 0 ? "1st" : rank === 1 ? "2nd" : rank === 2 ? "3rd" : `${rank + 1}th`;
    for (let g = 0; g < G; g++) {
      qualifiers.push({ label: `${rankLabel} · ${groups[g].name}`, seed: seedNum++ });
    }
  }

  const N = qualifiers.length;
  let size = 1;
  while (size < N) size *= 2;
  const numByes = size - N;
  const numRounds = Math.log2(size);

  // Step 2: Generate CORRECT standard seeded bracket positions
  // Algorithm: start with [1, 2], then expand by inserting complement after each element
  // [1,2] -> [1,4,2,3] -> [1,8,4,5,2,7,3,6] -> [1,16,8,9,4,13,5,12,2,15,7,10,3,14,6,11]
  // This gives: M1=S1vsS16, M2=S8vsS9, M3=S4vsS13, M4=S5vsS12, M5=S2vsS15, ...
  // S1 and S2 are in OPPOSITE halves -> can only meet in FINAL ✓
  function buildSeededPositions(n: number): number[] {
    let bracket = [1, 2];
    while (bracket.length < n) {
      const newSize = bracket.length * 2;
      const next: number[] = [];
      for (const s of bracket) {
        next.push(s);
        next.push(newSize + 1 - s);
      }
      bracket = next;
    }
    return bracket;
  }

  const seedAtPos = buildSeededPositions(size);

  // Step 3: Build slot array — map each position to a qualifier or BYE
  // Positions where seedAtPos[i] > N are padding BYEs (bracket is bigger than qualifiers)
  const slotArray: BracketSlot[] = seedAtPos.map(seed => {
    if (seed > N) return { label: "BYE", isBye: true, seed };
    return { label: qualifiers[seed - 1].label, isBye: false, seed };
  });

  // Step 4: Apply byes for top seeds (S1..S_numByes get byes)
  // Their OPPONENT slot becomes BYE so they auto-advance
  if (numByes > 0) {
    for (let seed = 1; seed <= numByes; seed++) {
      const pos = seedAtPos.indexOf(seed);
      if (pos === -1) continue;
      const opponentPos = pos % 2 === 0 ? pos + 1 : pos - 1;
      slotArray[opponentPos] = { label: "BYE", isBye: true, seed: 9999 };
    }
  }

  // Step 4b: Fix same-group clashes in R1
  // When byes are involved, the last group winner may be paired with the last runner-up
  // from the SAME group (e.g. 1st K vs 2nd K). Fix by swapping runner-up opponents.
  // We only swap the "slot2" (runner-up side) of clashing matches with non-clashing ones.
  // Group index: seeds 1..G are group winners (group = seed-1), seeds G+1..N are runners-up (group = seed-G-1)
  const getGroupIdx = (seed: number): number => {
    if (seed <= 0 || seed > N) return -1;
    if (seed <= G) return seed - 1;
    return seed - G - 1;
  };

  // Find real R1 matches (both slots non-BYE) and detect clashes
  for (let pass = 0; pass < G; pass++) { // max passes = number of groups
    let foundClash = false;
    for (let i = 0; i < size; i += 2) {
      const s1 = slotArray[i], s2 = slotArray[i + 1];
      if (s1.isBye || s2.isBye) continue;
      const g1 = getGroupIdx(s1.seed), g2 = getGroupIdx(s2.seed);
      if (g1 === g2 && g1 !== -1) {
        // Same-group clash — find another real match to swap slot2 with
        for (let j = 0; j < size; j += 2) {
          if (j === i) continue;
          const t1 = slotArray[j], t2 = slotArray[j + 1];
          if (t1.isBye || t2.isBye) continue;
          const tg1 = getGroupIdx(t1.seed), tg2 = getGroupIdx(t2.seed);
          // Swap slot2 of match i with slot2 of match j, if it resolves the clash
          // and doesn't create a new clash
          const newG_i2 = tg2, newG_j2 = g2;
          if (g1 !== newG_i2 && tg1 !== newG_j2) {
            // Safe to swap
            const tmp = slotArray[i + 1];
            slotArray[i + 1] = slotArray[j + 1];
            slotArray[j + 1] = tmp;
            foundClash = true;
            break;
          }
        }
        if (foundClash) break;
      }
    }
    if (!foundClash) break;
  }

  // Step 5: Build first-round matches
  const firstRoundMatches: BracketMatch[] = [];
  for (let i = 0; i < size; i += 2) {
    firstRoundMatches.push({
      id: `r0-m${i / 2}`,
      round: 0,
      matchNum: i / 2 + 1,
      slot1: slotArray[i],
      slot2: slotArray[i + 1],
    });
  }

  // Step 6: Build subsequent rounds with correct feeder match references
  const result: BracketMatch[] = [...firstRoundMatches];
  let prevRoundMatches = firstRoundMatches;
  let nextMatchNum = firstRoundMatches.length + 1;

  for (let r = 1; r < numRounds; r++) {
    const nextRoundMatches: BracketMatch[] = [];
    for (let m = 0; m < prevRoundMatches.length / 2; m++) {
      const feeder1 = prevRoundMatches[m * 2];
      const feeder2 = prevRoundMatches[m * 2 + 1];
      nextRoundMatches.push({
        id: `r${r}-m${m}`,
        round: r,
        matchNum: nextMatchNum++,
        slot1: { label: `W M${feeder1.matchNum}`, isBye: false, seed: 0 },
        slot2: { label: `W M${feeder2.matchNum}`, isBye: false, seed: 0 },
      });
    }
    result.push(...nextRoundMatches);
    prevRoundMatches = nextRoundMatches;
  }

  return result;
}

function getRoundLabel(round: number, totalRounds: number): string {
  const fromEnd = totalRounds - 1 - round;
  if (fromEnd === 0) return "Final";
  if (fromEnd === 1) return "Semi-Final";
  if (fromEnd === 2) return "Quarter-Final";
  if (fromEnd === 3) return "Round of 16";
  if (fromEnd === 4) return "Round of 32";
  return "Round of 64";
}

function WimbledonBracket({ matches, totalRounds }: { matches: BracketMatch[]; totalRounds: number }) {
  const rounds: Record<number, BracketMatch[]> = {};
  for (const m of matches) {
    if (!rounds[m.round]) rounds[m.round] = [];
    rounds[m.round].push(m);
  }

  const CARD_H = 72;
  const CARD_W = 192;
  const GAP_X = 40;
  const BASE_GAP_Y = 8;

  const r0Count = rounds[0]?.length ?? 1;
  const totalH = r0Count * CARD_H + (r0Count - 1) * BASE_GAP_Y + 48;

  return (
    <div style={{ overflowX: "auto", overflowY: "auto", maxHeight: "82vh" }}>
      <div style={{ position: "relative", width: totalRounds * (CARD_W + GAP_X) + 20, height: totalH, minWidth: 600 }}>
        {Object.entries(rounds).map(([roundStr, rMatches]) => {
          const round = parseInt(roundStr);
          const isFinal = round === totalRounds - 1;
          const factor = Math.pow(2, round);
          const cardGap = BASE_GAP_Y * factor + CARD_H * (factor - 1);
          const topOffset = (factor - 1) * (CARD_H + BASE_GAP_Y) / 2;

          return rMatches.map((match, idx) => {
            const x = round * (CARD_W + GAP_X);
            const y = topOffset + idx * (CARD_H + cardGap) + 28;
            const centerY = y + CARD_H / 2;
            const nextCenterY = y + CARD_H + cardGap + CARD_H / 2;
            const midY = (centerY + nextCenterY) / 2;

            return (
              <div key={match.id}>
                {round < totalRounds - 1 && (
                  <svg style={{ position: "absolute", left: 0, top: 0, width: "100%", height: "100%", pointerEvents: "none", overflow: "visible" }}>
                    <line x1={x + CARD_W} y1={centerY} x2={x + CARD_W + GAP_X / 2} y2={centerY}
                      stroke="#C9A84C" strokeWidth="1.5" strokeOpacity="0.5" />
                    {idx % 2 === 0 && (
                      <>
                        <line x1={x + CARD_W + GAP_X / 2} y1={centerY} x2={x + CARD_W + GAP_X / 2} y2={nextCenterY}
                          stroke="#C9A84C" strokeWidth="1.5" strokeOpacity="0.5" />
                        <line x1={x + CARD_W + GAP_X / 2} y1={midY} x2={x + CARD_W + GAP_X} y2={midY}
                          stroke="#C9A84C" strokeWidth="1.5" strokeOpacity="0.5" />
                      </>
                    )}
                  </svg>
                )}

                <div style={{
                  position: "absolute", left: x, top: y,
                  width: CARD_W, height: CARD_H,
                  borderRadius: 8, overflow: "hidden",
                  border: isFinal ? "2px solid #C9A84C" : "1px solid #E8E0D0",
                  boxShadow: isFinal ? "0 4px 20px rgba(201,168,76,0.25)" : "0 1px 4px rgba(0,0,0,0.07)",
                  background: "white",
                }}>
                  <MatchSlot slot={match.slot1} matchNum={match.matchNum} />
                  <div style={{ height: 1, background: "#E8E0D0" }} />
                  <MatchSlot slot={match.slot2} matchNum={match.matchNum} />
                </div>
              </div>
            );
          });
        })}

        {Object.entries(rounds).map(([roundStr]) => {
          const round = parseInt(roundStr);
          const isFinal = round === totalRounds - 1;
          const x = round * (CARD_W + GAP_X);
          return (
            <div key={`h${round}`} style={{ position: "absolute", left: x, top: 4, width: CARD_W, textAlign: "center" }}>
              <span style={{
                display: "inline-block", fontSize: 9, fontWeight: 700,
                letterSpacing: "0.1em", textTransform: "uppercase",
                padding: "2px 10px", borderRadius: 20,
                background: isFinal ? "#C9A84C" : "#F0EDE8",
                color: isFinal ? "#1A3318" : "#8A8070",
              }}>
                {getRoundLabel(round, totalRounds)}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function MatchSlot({ slot, matchNum }: { slot: BracketSlot; matchNum: number }) {
  if (slot.isBye) {
    return (
      <div style={{ height: "50%", display: "flex", alignItems: "center", padding: "0 10px", background: "#F9FAFB" }}>
        <span style={{ fontSize: 10, fontStyle: "italic", color: "#9CA3AF" }}>BYE</span>
      </div>
    );
  }
  const isGroupSlot = slot.label.includes("·");
  return (
    <div style={{ height: "50%", display: "flex", alignItems: "center", padding: "0 8px", gap: 6, background: "white" }}>
      {isGroupSlot && slot.seed > 0 && slot.seed <= 8 && (
        <div style={{
          width: 18, height: 18, borderRadius: "50%", flexShrink: 0,
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 8, fontWeight: 800,
          background: "#C9A84C", color: "#1A3318",
        }}>
          {slot.seed}
        </div>
      )}
      <div style={{ minWidth: 0, flex: 1 }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: "#1A3318" }}>TBD</div>
        <div style={{ fontSize: 9, color: "#8A8070", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
          {slot.label}
        </div>
      </div>
    </div>
  );
}

export default function DrawPage() {
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [teams, setTeams] = useState<Team[]>([]);
  const [fileName, setFileName] = useState("");
  const [numGroups, setNumGroups] = useState(8);
  const [qualifiersPerGroup, setQualifiersPerGroup] = useState(2);
  const [scoringFormat, setScoringFormat] = useState("Best of 3, to 11");
  const [groups, setGroups] = useState<Group[]>([]);
  const [bracketMatches, setBracketMatches] = useState<BracketMatch[]>([]);
  const [activeGroupTab, setActiveGroupTab] = useState(0);
  const fileRef = useRef<HTMLInputElement>(null);

  function handleFile(file: File) {
    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      setTeams(parseCSV(text));
      setStep(2);
    };
    reader.readAsText(file);
  }

  function generateGroups() {
    setGroups(snakeSeed(teams, numGroups));
    setStep(3);
  }

  function generateKnockout() {
    setBracketMatches(buildBracket(groups, qualifiersPerGroup));
    setStep(4);
  }

  const totalQualifiers = numGroups * qualifiersPerGroup;
  let bracketSize = 1;
  while (bracketSize < totalQualifiers) bracketSize *= 2;
  const totalRounds = Math.log2(bracketSize);
  const numByes = bracketSize - totalQualifiers;

  return (
    <div className="min-h-screen" style={{ background: "#F8F4EE" }}>
      <div style={{ background: "linear-gradient(135deg, #1A3318 0%, #2D5A27 100%)" }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-5">
          <div className="flex items-center gap-4">
            <Link href="/admin" className="text-white/50 hover:text-white transition-colors">
              <ChevronLeft size={20} />
            </Link>
            <div>
              <div className="text-xs font-semibold uppercase tracking-widest mb-0.5" style={{ color: "rgba(201,168,76,0.6)" }}>Admin · Draw Generation</div>
              <h1 className="font-display text-2xl font-bold text-white">Tournament Draw</h1>
            </div>
          </div>
          <div className="flex items-center gap-2 mt-5">
            {[{ n: 1, label: "Upload CSV" }, { n: 2, label: "Configure" }, { n: 3, label: "Group Draw" }, { n: 4, label: "Knockout" }].map(({ n, label }, i) => (
              <div key={n} className="flex items-center gap-2">
                <div className="flex items-center gap-1.5">
                  <div className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold"
                    style={step >= n ? { background: "#C9A84C", color: "#1A3318" } : { background: "rgba(255,255,255,0.1)", color: "rgba(255,255,255,0.4)" }}>
                    {n}
                  </div>
                  <span className="text-xs font-medium hidden sm:block"
                    style={{ color: step >= n ? "rgba(255,255,255,0.9)" : "rgba(255,255,255,0.35)" }}>
                    {label}
                  </span>
                </div>
                {i < 3 && <div className="w-8 h-px" style={{ background: "rgba(255,255,255,0.15)" }} />}
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        {step === 1 && (
          <div className="max-w-2xl mx-auto">
            <div className="bg-white rounded-3xl p-8 text-center" style={{ border: "2px dashed rgba(201,168,76,0.3)" }}>
              <div className="w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4" style={{ background: "rgba(201,168,76,0.1)" }}>
                <Upload size={28} style={{ color: "#C9A84C" }} />
              </div>
              <h2 className="font-display text-xl font-bold mb-2" style={{ color: "#1A3318" }}>Upload Entries CSV</h2>
              <p className="text-sm mb-6" style={{ color: "#8A8070" }}>
                Upload your tournament entries CSV with Player 1, Player 2, DUPR ratings, and Ranking columns.
              </p>
              <input ref={fileRef} type="file" accept=".csv" className="hidden"
                onChange={(e) => e.target.files?.[0] && handleFile(e.target.files[0])} />
              <button onClick={() => fileRef.current?.click()}
                className="px-8 py-3.5 rounded-2xl font-semibold text-sm text-white"
                style={{ background: "#1A3318" }}>
                Choose CSV File
              </button>
              <div className="mt-6 p-4 rounded-xl text-left" style={{ background: "#F8F4EE" }}>
                <div className="text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: "#8A8070" }}>Expected columns</div>
                <code className="text-xs" style={{ color: "#1A3318" }}>
                  Player 1, Player 1 Rating, Player 1 DUPR id, Contact,<br />
                  Player 2, Player 2 Rating, Player 2 DUPR id, Contact, Ranking
                </code>
              </div>
            </div>
          </div>
        )}

        {step === 2 && (
          <div className="grid lg:grid-cols-2 gap-6">
            <div className="bg-white rounded-3xl p-6" style={{ border: "1px solid rgba(232,224,208,0.8)" }}>
              <div className="flex items-center gap-2 mb-5">
                <div className="w-8 h-8 rounded-xl flex items-center justify-center" style={{ background: "rgba(201,168,76,0.12)" }}>
                  <Trophy size={15} style={{ color: "#C9A84C" }} />
                </div>
                <h2 className="font-display text-lg font-bold" style={{ color: "#1A3318" }}>Draw Configuration</h2>
              </div>
              <div className="space-y-5">
                <div>
                  <label className="block text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: "#8A8070" }}>File Loaded</label>
                  <div className="flex items-center gap-2 px-3 py-2.5 rounded-xl" style={{ background: "#F8F4EE" }}>
                    <span className="text-sm font-medium" style={{ color: "#1A3318" }}>{fileName}</span>
                    <span className="ml-auto px-2 py-0.5 rounded-full text-xs font-bold" style={{ background: "rgba(201,168,76,0.15)", color: "#A8872E" }}>{teams.length} teams</span>
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: "#8A8070" }}>Number of Groups</label>
                  <div className="flex gap-2 flex-wrap">
                    {[4, 6, 8, 10, 12].map((n) => (
                      <button key={n} onClick={() => setNumGroups(n)}
                        className="px-4 py-2 rounded-xl text-sm font-semibold"
                        style={numGroups === n ? { background: "#1A3318", color: "white" } : { background: "#F8F4EE", color: "#1A3318", border: "1px solid rgba(232,224,208,0.8)" }}>
                        {n}
                      </button>
                    ))}
                    <input type="number" min={2} max={26} value={numGroups}
                      onChange={(e) => setNumGroups(parseInt(e.target.value) || 4)}
                      className="w-16 px-3 py-2 rounded-xl text-sm font-semibold text-center focus:outline-none"
                      style={{ border: "1px solid rgba(232,224,208,0.8)", color: "#1A3318" }} />
                  </div>
                  <p className="text-xs mt-1.5" style={{ color: "#8A8070" }}>
                    {teams.length} teams → {numGroups} groups (~{Math.ceil(teams.length / numGroups)} per group)
                  </p>
                </div>
                <div>
                  <label className="block text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: "#8A8070" }}>Teams Qualifying per Group</label>
                  <div className="flex gap-2">
                    {[1, 2, 3, 4].map((n) => (
                      <button key={n} onClick={() => setQualifiersPerGroup(n)}
                        className="px-4 py-2 rounded-xl text-sm font-semibold"
                        style={qualifiersPerGroup === n ? { background: "#1A3318", color: "white" } : { background: "#F8F4EE", color: "#1A3318", border: "1px solid rgba(232,224,208,0.8)" }}>
                        Top {n}
                      </button>
                    ))}
                  </div>
                  <p className="text-xs mt-1.5" style={{ color: "#8A8070" }}>
                    {totalQualifiers} teams → bracket of {bracketSize}
                    {numByes > 0 ? ` · top ${numByes} seeds get byes` : " · no byes (perfect bracket)"}
                  </p>
                </div>
                <div>
                  <label className="block text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: "#8A8070" }}>Scoring Format</label>
                  <select value={scoringFormat} onChange={(e) => setScoringFormat(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl text-sm focus:outline-none"
                    style={{ border: "1px solid rgba(232,224,208,0.8)", color: "#1A3318", background: "white" }}>
                    <option>Best of 3, to 11</option>
                    <option>Best of 1, to 11</option>
                    <option>Best of 3, to 15</option>
                    <option>Best of 1, to 15</option>
                    <option>Best of 3, to 21</option>
                    <option>Best of 1, to 21</option>
                  </select>
                </div>
                <button onClick={generateGroups}
                  className="w-full py-3.5 rounded-2xl font-bold"
                  style={{ background: "#C9A84C", color: "#1A3318" }}>
                  Generate Group Draw →
                </button>
              </div>
            </div>

            <div className="bg-white rounded-3xl overflow-hidden" style={{ border: "1px solid rgba(232,224,208,0.8)" }}>
              <div className="px-5 py-4" style={{ borderBottom: "1px solid rgba(232,224,208,0.8)", background: "#F8F4EE" }}>
                <h3 className="font-display font-bold" style={{ color: "#1A3318" }}>Seeded Teams ({teams.length})</h3>
              </div>
              <div className="overflow-y-auto" style={{ maxHeight: "480px" }}>
                <table className="w-full">
                  <thead>
                    <tr style={{ borderBottom: "1px solid rgba(232,224,208,0.5)", background: "#FDFAF5" }}>
                      <th className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide" style={{ color: "#8A8070" }}>Seed</th>
                      <th className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide" style={{ color: "#8A8070" }}>Team</th>
                      <th className="px-4 py-2.5 text-right text-xs font-semibold uppercase tracking-wide" style={{ color: "#8A8070" }}>Rating</th>
                    </tr>
                  </thead>
                  <tbody>
                    {teams.map((t) => (
                      <tr key={t.seed} className="hover:bg-[#F8F4EE]" style={{ borderBottom: "1px solid rgba(232,224,208,0.4)" }}>
                        <td className="px-4 py-2.5">
                          <span className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold"
                            style={t.seed <= 4 ? { background: "#C9A84C", color: "#1A3318", display: "inline-flex" } : { background: "#F8F4EE", color: "#8A8070", display: "inline-flex" }}>
                            {t.seed}
                          </span>
                        </td>
                        <td className="px-4 py-2.5">
                          <div className="text-sm font-medium" style={{ color: "#1A3318" }}>{t.player1}</div>
                          <div className="text-xs" style={{ color: "#8A8070" }}>{t.player2}</div>
                        </td>
                        <td className="px-4 py-2.5 text-right">
                          <span className="text-sm font-bold tabular-nums" style={{ color: "#C9A84C" }}>{t.teamRating.toFixed(3)}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {step === 3 && (
          <div>
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="font-display text-2xl font-bold" style={{ color: "#1A3318" }}>Group Draw</h2>
                <p className="text-sm mt-0.5" style={{ color: "#8A8070" }}>
                  {groups.length} groups · {scoringFormat} · Top {qualifiersPerGroup} qualify
                </p>
              </div>
              <div className="flex gap-2">
                <button onClick={() => setStep(2)}
                  className="px-4 py-2 rounded-xl text-sm font-semibold"
                  style={{ border: "1px solid rgba(232,224,208,0.8)", color: "#1A3318", background: "white" }}>
                  ← Reconfigure
                </button>
                <button onClick={generateKnockout}
                  className="px-5 py-2 rounded-xl text-sm font-bold"
                  style={{ background: "#C9A84C", color: "#1A3318" }}>
                  Generate Knockout →
                </button>
              </div>
            </div>

            <div className="flex gap-1 flex-wrap mb-5" style={{ borderBottom: "1px solid rgba(232,224,208,0.8)" }}>
              {groups.map((g, i) => (
                <button key={i} onClick={() => setActiveGroupTab(i)}
                  className="px-4 py-2 text-sm font-medium border-b-2 -mb-px"
                  style={activeGroupTab === i ? { borderColor: "#C9A84C", color: "#C9A84C" } : { borderColor: "transparent", color: "#8A8070" }}>
                  {g.name}
                </button>
              ))}
            </div>

            {groups[activeGroupTab] && (
              <div className="grid lg:grid-cols-2 gap-6">
                <div className="bg-white rounded-2xl overflow-hidden" style={{ border: "1px solid rgba(232,224,208,0.8)" }}>
                  <div className="px-5 py-3.5 flex items-center justify-between" style={{ background: "#1A3318" }}>
                    <h3 className="font-display font-bold text-white">{groups[activeGroupTab].name}</h3>
                    <span className="text-xs" style={{ color: "rgba(201,168,76,0.7)" }}>{groups[activeGroupTab].teams.length} teams</span>
                  </div>
                  <table className="w-full">
                    <thead>
                      <tr style={{ borderBottom: "1px solid rgba(232,224,208,0.5)", background: "#F8F4EE" }}>
                        <th className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide" style={{ color: "#8A8070" }}>Seed</th>
                        <th className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide" style={{ color: "#8A8070" }}>Team</th>
                        <th className="px-4 py-2.5 text-right text-xs font-semibold uppercase tracking-wide" style={{ color: "#8A8070" }}>DUPR</th>
                      </tr>
                    </thead>
                    <tbody>
                      {groups[activeGroupTab].teams.map((t, i) => (
                        <tr key={t.seed} style={{ borderBottom: "1px solid rgba(232,224,208,0.4)", background: i < qualifiersPerGroup ? "#F0FDF4" : "white" }}>
                          <td className="px-4 py-3">
                            <span className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold"
                              style={t.seed <= 4 ? { background: "#C9A84C", color: "#1A3318", display: "inline-flex" } : { background: "#F8F4EE", color: "#8A8070", display: "inline-flex" }}>
                              {t.seed}
                            </span>
                          </td>
                          <td className="px-4 py-3">
                            <div className="text-sm font-semibold" style={{ color: "#1A3318" }}>{t.player1}</div>
                            <div className="text-xs" style={{ color: "#8A8070" }}>{t.player2}</div>
                            {i < qualifiersPerGroup && (
                              <span className="text-[10px] font-semibold mt-0.5 inline-block" style={{ color: "#16A34A" }}>
                                {i === 0 ? "Qualifies 1st" : i === 1 ? "Qualifies 2nd" : i === 2 ? "Qualifies 3rd" : `Qualifies ${i + 1}th`}
                              </span>
                            )}
                          </td>
                          <td className="px-4 py-3 text-right font-bold tabular-nums text-sm" style={{ color: "#C9A84C" }}>
                            {t.teamRating.toFixed(3)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <div className="bg-white rounded-2xl overflow-hidden" style={{ border: "1px solid rgba(232,224,208,0.8)" }}>
                  <div className="px-5 py-3.5" style={{ background: "#F8F4EE", borderBottom: "1px solid rgba(232,224,208,0.8)" }}>
                    <h3 className="font-display font-bold" style={{ color: "#1A3318" }}>Fixtures</h3>
                    <p className="text-xs mt-0.5" style={{ color: "#8A8070" }}>{scoringFormat}</p>
                  </div>
                  <div className="divide-y" style={{ borderColor: "rgba(232,224,208,0.5)" }}>
                    {(() => {
                      const grpTeams = groups[activeGroupTab].teams;
                      const fixtures: { t1: Team; t2: Team }[] = [];
                      for (let i = 0; i < grpTeams.length; i++)
                        for (let j = i + 1; j < grpTeams.length; j++)
                          fixtures.push({ t1: grpTeams[i], t2: grpTeams[j] });
                      return fixtures.map((f, idx) => (
                        <div key={idx} className="px-5 py-3 flex items-center gap-3">
                          <span className="text-xs font-bold w-5 text-center" style={{ color: "#8A8070" }}>{idx + 1}</span>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 text-sm flex-wrap">
                              <span className="font-medium truncate" style={{ color: "#1A3318" }}>{f.t1.player1} / {f.t1.player2}</span>
                              <span className="text-xs flex-shrink-0" style={{ color: "#C9A84C" }}>vs</span>
                              <span className="font-medium truncate" style={{ color: "#1A3318" }}>{f.t2.player1} / {f.t2.player2}</span>
                            </div>
                          </div>
                          <div className="flex gap-1 flex-shrink-0">
                            <span className="text-xs px-1.5 py-0.5 rounded" style={{ background: "#F8F4EE", color: "#8A8070" }}>S{f.t1.seed}</span>
                            <span className="text-xs px-1.5 py-0.5 rounded" style={{ background: "#F8F4EE", color: "#8A8070" }}>S{f.t2.seed}</span>
                          </div>
                        </div>
                      ));
                    })()}
                  </div>
                </div>
              </div>
            )}

            <div className="mt-8">
              <h3 className="font-display text-lg font-bold mb-4" style={{ color: "#1A3318" }}>All Groups Overview</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {groups.map((g, i) => (
                  <button key={i} onClick={() => setActiveGroupTab(i)}
                    className="bg-white rounded-2xl p-4 text-left hover:shadow-md"
                    style={{ border: activeGroupTab === i ? "2px solid #C9A84C" : "1px solid rgba(232,224,208,0.8)" }}>
                    <div className="font-display font-bold mb-2" style={{ color: "#1A3318" }}>{g.name}</div>
                    {g.teams.slice(0, 3).map((t) => (
                      <div key={t.seed} className="flex items-center gap-1.5 mb-1">
                        <span className="text-[10px] font-bold w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0"
                          style={{ background: t.seed <= 4 ? "#C9A84C" : "#F8F4EE", color: t.seed <= 4 ? "#1A3318" : "#8A8070" }}>
                          {t.seed}
                        </span>
                        <span className="text-xs truncate" style={{ color: "#1A3318" }}>{t.player1}</span>
                      </div>
                    ))}
                    {g.teams.length > 3 && <div className="text-xs mt-1" style={{ color: "#8A8070" }}>+{g.teams.length - 3} more</div>}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {step === 4 && (
          <div>
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="font-display text-2xl font-bold" style={{ color: "#1A3318" }}>Knockout Draw</h2>
                <p className="text-sm mt-0.5" style={{ color: "#8A8070" }}>
                  {totalQualifiers} qualifiers · bracket of {bracketSize}
                  {numByes > 0 ? ` · top ${numByes} seeds get byes` : " · no byes"}
                  · S1 vs S2 in Final only
                </p>
              </div>
              <div className="flex gap-2">
                <button onClick={() => setStep(3)}
                  className="px-4 py-2 rounded-xl text-sm font-semibold"
                  style={{ border: "1px solid rgba(232,224,208,0.8)", color: "#1A3318", background: "white" }}>
                  ← Groups
                </button>
                <button className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold"
                  style={{ background: "#1A3318", color: "white" }}>
                  <Download size={14} /> Export
                </button>
              </div>
            </div>

            <div className="bg-white rounded-3xl overflow-hidden" style={{ border: "1px solid rgba(232,224,208,0.8)" }}>
              <div className="px-6 py-4 flex items-center gap-3" style={{ background: "#1A3318" }}>
                <Trophy size={18} style={{ color: "#C9A84C" }} />
                <span className="font-display font-bold text-white">Knockout Bracket</span>
                <div className="ml-auto text-xs" style={{ color: "rgba(255,255,255,0.4)" }}>
                  Standard seeding · S1 top · S2 bottom · fills after group stage
                </div>
              </div>
              <div className="p-6" style={{ background: "#FDFAF5" }}>
                <WimbledonBracket matches={bracketMatches} totalRounds={totalRounds} />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
